<a href="https://colab.research.google.com/github/tuazonhai/CPE-310-2526A/blob/main/Hands_on_Activity_6_2_Getting_Started_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**EXERCISES**

**EXERCISES - 2019_Yellow_Taxi_Trip_Data**

In [1]:
# Exercise 1.1 Create a DataFrame by reading in the 2019_Yellow_Taxi_Trip_Data.csv file. Examine the first 5 rows.
import pandas as pd
taxi_df = pd.read_csv("/2019_Yellow_Taxi_Trip_Data(1)(1).csv")

taxi_df.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,N,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,N,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,N,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,N,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,N,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5

In [2]:
# Exercise 1.2 Find the dimensions (number of rows and number of columns) in the data.

taxi_df.shape

(10000, 18)

In [3]:
# Exercise 1.3 Using the data in the 2019_Yellow_Taxi_Trip_Data.csv file, calculate summary statistics for the fare_amount, tip_amount, tolls_amount, and total_amount columns.

taxi_df[["fare_amount", "tip_amount", "tolls_amount", "total_amount"]].describe()

        fare_amount    tip_amount  tolls_amount  total_amount
count  10000.000000  10000.000000  10000.000000  10000.000000
mean      15.106313      2.634494      0.623447     22.564659
std       13.954762      3.409800      6.437507     19.209255
min      -52.000000      0.000000     -6.120000    -65.920000
25%        7.000000      0.000000      0.000000     12.375000
50%       10.000000      2.000000      0.000000     16.300000
75%       16.000000      3.250000      0.000000     22.880000
max      176.000000     43.000000    612.000000    671.800000

In [4]:
# Exercise 1.4 Isolate the fare_amount, tip_amount, tolls_amount, and total_amount for the longest trip by distance (trip_distance).

taxi_df.loc[taxi_df["trip_distance"].idxmax(), ['fare_amount', 'tip_amount', "tolls_amount", 'total_amount']]

fare_amount      176.0
tip_amount       18.29
tolls_amount      6.12
total_amount    201.21
Name: 8338, dtype: object

**SUPPLEMENTARY ACTIVITY - AUTOMOBILE**

In [5]:
# Exercise 1.1 Create a DataFrame by reading in the 21985 Auto Imports - Excel Data Export_ 1985 Auto Imports.csv file. Examine the first 5 rows.

import pandas as pd
auto_imports = pd.read_csv("/Excel Data Export_ 1985 Auto Imports - Excel Data Export_ 1985 Auto Imports.csv")

auto_imports.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [6]:
# Exercise 1.2 Find the dimensions (number of rows and number of columns) in the data.

auto_imports.shape

(14, 26)

In [8]:
# Exercise 1.3 Using the data in the 1985 Auto Imports - Excel Data Export_ 1985 Auto Imports.csv file, calculate summary statistics.

auto_imports.describe(include = "all")

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,14.000000,14,14,14,14,14,14,14,14,14.000000,...,14.000000,14,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14
unique,NaN,5,3,1,2,2,4,3,1,NaN,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
top,NaN,?,audi,gas,std,two,sedan,rwd,front,NaN,...,NaN,mpfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16500
freq,NaN,6,7,14,12,7,9,7,14,NaN,...,NaN,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
mean,1.285714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.457143,...,133.642857,NaN,3.246429,3.186429,8.671429,119.071429,5257.142857,20.071429,25.928571,NaN
std,1.069045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.501149,...,17.899751,NaN,0.214928,0.305252,0.668441,18.971494,498.404046,2.335818,2.973325,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.600000,...,108.000000,NaN,2.680000,2.680000,7.000000,101.000000,4250.000000,16.000000,20.000000,NaN
25%,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.425000,...,130.000000,NaN,3.190000,2.897500,8.500000,110.000000,5000.000000,19.000000,25.000000,NaN
50%,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.500000,...,133.500000,NaN,3.190000,3.400000,8.800000,111.000000,5500.000000,20.000000,26.500000,NaN
75%,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.200000,...,136.000000,NaN,3.430000,3.400000,9.000000,121.000000,5500.000000,21.000000,28.000000,NaN
max,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.800000,...,164.000000,NaN,3.500000,3.470000,10.000000,160.000000,5800.000000,24.000000,30.000000,NaN

In [7]:
# Exercise 1.4 Isolate the make, engine-size, horsepower, city-mpg, highway-mpg, and price.

auto_imports.loc[auto_imports['price'].idxmax(), ['make', 'engine-size', 'horsepower', 'city-mpg', 'highway-mpg', 'price']]

make           audi
engine-size     131
horsepower      160
city-mpg         16
highway-mpg      22
price             ?
Name: 9, dtype: object