<a href="https://colab.research.google.com/github/tuazonhai/CPE-310-2526A/blob/main/TUAZON_Supplementary_Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SUPPLEMENTARY ACTIVITY**

In [ ]:
# Exercise 1.1 Create a DataFrame by reading in the 21985 Auto Imports - Excel Data Export_ 1985 Auto Imports.csv file. Examine the first 5 rows.

import pandas as pd
auto_imports = pd.read_csv("/1985 Auto Imports - Excel Data Export_ 1985 Auto Imports.csv")

auto_imports.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [ ]:
# Exercise 1.2 Find the dimensions (number of rows and number of columns) in the data.

auto_imports.shape

(14, 26)

In [ ]:
# Exercise 1.3 Using the data in the 1985 Auto Imports - Excel Data Export_ 1985 Auto Imports.csv file, calculate summary statistics.

auto_imports.describe(include = "all")

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,14.000000,14,14,14,14,14,14,14,14,14.000000,...,14.000000,14,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14
unique,NaN,5,3,1,2,2,4,3,1,NaN,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
top,NaN,?,audi,gas,std,two,sedan,rwd,front,NaN,...,NaN,mpfi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16500
freq,NaN,6,7,14,12,7,9,7,14,NaN,...,NaN,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
mean,1.285714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.457143,...,133.642857,NaN,3.246429,3.186429,8.671429,119.071429,5257.142857,20.071429,25.928571,NaN
std,1.069045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.501149,...,17.899751,NaN,0.214928,0.305252,0.668441,18.971494,498.404046,2.335818,2.973325,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.600000,...,108.000000,NaN,2.680000,2.680000,7.000000,101.000000,4250.000000,16.000000,20.000000,NaN
25%,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.425000,...,130.000000,NaN,3.190000,2.897500,8.500000,110.000000,5000.000000,19.000000,25.000000,NaN
50%,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.500000,...,133.500000,NaN,3.190000,3.400000,8.800000,111.000000,5500.000000,20.000000,26.500000,NaN
75%,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.200000,...,136.000000,NaN,3.430000,3.400000,9.000000,121.000000,5500.000000,21.000000,28.000000,NaN
max,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.800000,...,164.000000,NaN,3.500000,3.470000,10.000000,160.000000,5800.000000,24.000000,30.000000,NaN

In [ ]:
# Exercise 1.4 Isolate the make, engine-size, horsepower, city-mpg, highway-mpg, and price.

auto_imports.loc[auto_imports['price'].idxmax(), ['make', 'engine-size', 'horsepower', 'city-mpg', 'highway-mpg', 'price']]

make           audi
engine-size     131
horsepower      160
city-mpg         16
highway-mpg      22
price             ?
Name: 9, dtype: object